remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Brett Carlson
description: Welcome to my website, I post my projects and thoughts related to Computer Science and Cybersecurity here.
